<Project>
  <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
    <PackageVersion Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>
</Project>
